### ISSUE TITLE
Preheater service fails

### ISSUE THREAD

**Issue by NickSutton** [skodaconnect/homeassistant-skodaconnect#206]
I get this error when trying to set the pre-heater timer for the Enyaq IV:

````

This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/skodaconnect/__init__.py:282 
Integration: Skoda Connect (documentation, issues) 
First occurred: 14:10:52 (1 occurrences) 
Last logged: 14:10:52

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Could not find associated coordinator for given vehicle
Traceback (most recent call last):
  File "/config/custom_components/skodaconnect/__init__.py", line 280, in get_car
    dev_coordinator = hass.data[DOMAIN][conf_entry]['data'].coordinator
                      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '1379863f3a9e6a1bb696ebbbf92c5e70'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/skodaconnect/__init__.py", line 412, in set_pheater_duration
    car = await get_car(service_call)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/skodaconnect/__init__.py", line 282, in get_car
    raise SkodaConfigException('Could not find associated coordinator for given vehicle')
skodaconnect.exceptions.SkodaConfigException: Could not find associated coordinator for given vehicle
````

**Comment by dvx76** [comment]
Do you have other errors similar to this one for skodaconnect entities? It _looks_ like somehow you've got orphaned entities (maybe from a previous installation of the integration?). Not sure how it gets into this state.

In your homeassitant config directory you'll have a `.storage/core.entity_registry`  where you'll find all entities from the integration (search for `Skoda`). At least some will have `"config_entry_id": "1379863f3a9e6a1bb696ebbbf92c5e70"`.

That `config_entry_id` is being looked up in `.storage/core.config_entries` and not found (that's the `KeyError`). Presumably in that file you _do_  have a section (with a different `entry_id`) with the config of the integration. Look for `"domain": "skodaconnect"`.

**Comment by NickSutton** [comment]
Hi, no `.storage` folder in my config directory :-(

**Comment by srkoster** [comment]
Faced the same issue. 

I've looked into my config/.storage/core.entity_reigstry (using the Advanced SSH & Web Terminal add-on as the directory wasn't visible using the Studio Code Server add-on) and have found the key. It was a helper entity, based on one of the Skoda Connect entities. I've removed it for now and the error disappeared.
