### ISSUE TITLE
Turning off/on polling errors out the integration, making all sensors become unavailable

### ISSUE THREAD

**Issue by zandzpider** [skodaconnect/homeassistant-skodaconnect#285]
**Describe the bug**
Toggling data polling stops the integration from working, making all sensors unavailable.
The only way to get it back to working condition, is a restart of HA

The below logs are from a fresh reboot, and after some time, i disabled the polling resulting in an instant failure of the integration.

A full removal of vehicle, integration -> restart -> install integration has been done without any further success

**Latest working release**
Not sure when this stopped working, but i assume it came with one of the newer HA releases as it stopped not long ago

**Debug logs**
2024-05-14 22:07:03.434 DEBUG (MainThread) [skodaconnect.connection] Check if vehicle exists
2024-05-14 22:07:03.434 DEBUG (MainThread) [skodaconnect.connection] Adding vehicle ***********, with connectivities: ['REMOTE']
2024-05-14 22:07:03.434 DEBUG (MainThread) [skodaconnect.vehicle] Creating Vehicle class object with data {'vin': '***********', 'connectivities': ['REMOTE'], 'capabilities': ['AUTOMATION', 'CHARGING', 'CHARGING_STATIONS', 'AIR_CONDITIONING', 'DEALER_APPOINTMENT', 'DESTINATIONS', 'MAP_UPDATE', 'MEASUREMENTS', 'ONLINE_SPEECH', 'ONLINE_SPEECH_GPS', 'PARKING_INFORMATION', 'PARKING_POSITION', 'PLUG_AND_CHARGE', 'POI_SEARCH', 'ROADSIDE_ASSISTANT', 'ROUTING', 'STATE', 'TRAFFIC_INFORMATION', 'VEHICLE_HEALTH', 'VEHICLE_LIGHTS'], 'specification': {'title': 'Škoda Enyaq', 'model': 'Enyaq', 'modelYear': '2023', 'body': 'SUV', 'systemCode': 'UNKNOWN', 'systemModelId': '*******', 'engine': {'type': 'iV', 'powerInKW': 195}, 'battery': {'capacityInKWh': 77}, 'gearbox': {'type': 'E1A'}, 'trimLevel': 'iV 80X SPORTLINE', 'manufacturingDate': ''*******', 'maxChargingPowerInKW': 125}}
2024-05-14 22:07:03.434 DEBUG (MainThread) [custom_components.skodaconnect] Updating data from Skoda Connect
2024-05-14 22:07:03.670 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/***********/settings" returned with status code [200]
2024-05-14 22:07:03.699 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/charging/***********/settings" returned with status code [200]
2024-05-14 22:07:03.713 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/position/vehicles/'*******/parking-position" returned with status code [200]
2024-05-14 22:07:03.725 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/'*******/timers" returned with status code [200]
2024-05-14 22:07:03.733 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/charging/'*******/status" returned with status code [200]
2024-05-14 22:07:03.738 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/air-conditioning/'*******/status" returned with status code [200]
2024-05-14 22:07:03.739 INFO (MainThread) [skodaconnect.connection] Returning with data {'airConditioning': {'remainingTimeToReachTargetTemperatureInSeconds': 0, 'state': 'Off', 'trigger': 'OFF', 'windowsHeatingStatuses': [{'windowLocation': 'Front', 'state': 'Off'}, {'windowLocation': 'Rear', 'state': 'Off'}], 'seatHeatingSupport': {'frontLeftAvailable': True, 'frontRightAvailable': True, 'rearLeftAvailable': False, 'rearRightAvailable': False}}, 'airConditioningSettings': {'targetTemperatureInKelvin': 294.15, 'temperatureConversionTableUsed': 'CELSIUS_KELVIN', 'airConditioningAtUnlock': False, 'windowHeatingEnabled': True, 'zonesSettings': {'frontLeftEnabled': False, 'frontRightEnabled': False}}}
2024-05-14 22:07:03.746 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v1/charging/'*******/mode" returned with status code [200]
2024-05-14 22:07:03.764 DEBUG (MainThread) [skodaconnect.connection] Request for "https://api.connect.skoda-auto.cz/api/v2/vehicle-status/***********" returned with status code [200]
2024-05-14 22:07:03.765 DEBUG (MainThread) [custom_components.skodaconnect] Finished fetching skodaconnect data in 0.331 seconds (success: True)
2024-05-14 22:07:03.766 INFO (MainThread) [homeassistant.components.sensor] Setting up skodaconnect.sensor
2024-05-14 22:07:03.766 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up skodaconnect platform for sensor
File "/config/custom_components/skodaconnect/sensor.py", line 22, in async_setup_entry
2024-05-14 22:07:03.768 INFO (MainThread) [homeassistant.components.lock] Setting up skodaconnect.lock
2024-05-14 22:07:03.768 ERROR (MainThread) [homeassistant.components.lock] Error while setting up skodaconnect platform for lock
File "/config/custom_components/skodaconnect/lock.py", line 23, in async_setup_entry
2024-05-14 22:07:03.769 INFO (MainThread) [homeassistant.components.device_tracker] Setting up skodaconnect.device_tracker
2024-05-14 22:07:03.770 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up skodaconnect platform for device_tracker
File "/config/custom_components/skodaconnect/device_tracker.py", line 18, in async_setup_entry
2024-05-14 22:07:03.771 INFO (MainThread) [homeassistant.components.switch] Setting up skodaconnect.switch
2024-05-14 22:07:03.771 ERROR (MainThread) [homeassistant.components.switch] Error while setting up skodaconnect platform for switch
File "/config/custom_components/skodaconnect/switch.py", line 25, in async_setup_entry
2024-05-14 22:07:03.773 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up skodaconnect.binary_sensor
2024-05-14 22:07:03.773 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up skodaconnect platform for binary_sensor
File "/config/custom_components/skodaconnect/binary_sensor.py", line 22, in async_setup_entry

**Installation:**
Core
2024.5.3
Supervisor
2024.05.1
Operating System
12.3
Frontend
20240501.1

**Additional context**

**Comment by Croock83** [comment]
I have same issue. Additionally logs shows:
2024-05-16 09:21:24.517 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up skodaconnect platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/skodaconnect/device_tracker.py", line 18, in async_setup_entry
    data = hass.data[DOMAIN][entry.entry_id][DATA]

Folder /usr/src is completly gone.
