### ISSUE TITLE
Unable to pass initial configuration with error message

### ISSUE THREAD

**Issue by Steve-Lammas** [skodaconnect/homeassistant-skodaconnect#288]
**Please search issues in https://github.com/skodaconnect/skodaconnect and https://github.com/skodaconnect/homeassistant-skodaconnect for duplicates or fixes before reporting a new issue.**

**Describe the bug**
Initial setup after entering email address and password results in an immediate 'Error' bubble with no detail

**Is this working in MySkoda app?***
Logout and login in the MySkoda app, preferably on Android.
Make sure that you have the latest app updates, sometimes there's new consent needed that will only show in latest app version.

I can pull the vehicle through on the Android MySkoda app

**Latest working release**
No previous experience. New installation using HACS Release: 1.2.11 Library: 1.3.11

**Debug logs**

```
Logger: homeassistant.data_entry_flow
Source: data_entry_flow.py:817
First occurred: 15:07:27 (1 occurrences)
Last logged: 15:07:27

custom_components.skodaconnect.config_flow::SkodaConnectConfigFlow calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author

Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.skodaconnect.config_flow
Source: custom_components/skodaconnect/config_flow.py:117
integration: Skoda Connect ([documentation](https://github.com/skodaconnect/homeassistant-skodaconnect/blob/main/README.md), [issues](https://github.com/skodaconnect/homeassistant-skodaconnect/issues))
First occurred: 15:07:34 (1 occurrences)
Last logged: 15:07:34

Fetch vehicles failed with error: Invalid token "None"

Log Details (ERROR)
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 15:07:34 (1 occurrences)
Last logged: 15:07:34

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp_session/__init__.py", line 199, in factory
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 295, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 71, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 215, in get
    return await super().get(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 108, in get
    result = await self._flow_mgr.async_configure(flow_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 438, in _async_configure
    raise ValueError(
ValueError: Show progress can only transition to show progress or show progress done.
```

**Installation:**
 - Home Assistant variant: Hass OS 12.3 on Proxmox
 - Python version [e.g. 3.7, 3.8]
 - Python library versions ["python3 -m pip list"]

Core
2024.5.5
Supervisor
2024.05.2
Operating System 
12.3
Frontend
20240501.1

**Additional context**

None

**Comment by dvx76** [comment]
Hi,

Most users have now received the same email wrt the Essentials app EOL. We also know that for new vehicles/accounts the Essentials app, and consequently this integration, is already not working.

There are only a few active developers working on this integration but we are aware of this and we are (slowly) working on making the integration compatible with the new MySkoda app/API. There are no timelines and in fact no guarantee we will get this working. Please be patient and do not open new issues reporting the same thing.
