### ISSUE TITLE
skoda connect not working for new skoda

### ISSUE THREAD

**Issue by astrakid** [skodaconnect/homeassistant-skodaconnect#297]
hi,
when trying to connect my skoda enyaq with home assistant via skoda connect i am not successful. 
ha latest docker version.

error in skoda-connect-integration:

`2024-08-18 21:19:00.470 WARNING (SyncWorker_14) [homeassistant.loader] We found a custom integration skodaconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-18 21:19:54.424 ERROR (MainThread) [custom_components.skodaconnect.config_flow] Fetch vehicles failed with error: Invalid token "None"
2024-08-18 21:19:54.424 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 579, in _async_handle_step
    self._async_remove_flow_progress(flow.flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 497, in _async_remove_flow_progress
    raise UnknownFlow
homeassistant.data_entry_flow.UnknownFlow
2024-08-18 21:19:54.678 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 549, in call_configure
    await self._async_configure(flow.flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 437, in _async_configure
    raise ValueError(
ValueError: Show progress can only transition to show progress or show progress done.
2024-08-18 21:20:39.655 ERROR (MainThread) [custom_components.skodaconnect.config_flow] Fetch vehicles failed with error: `
i assume it is the same issue as for other 3rd party products (ioboker, evcc). evcc was able to solve it. 
the used password is correct.

regards,
andre

**Comment by dvx76** [comment]
Are you able to use the old Skoda Essentials app, or only the new MySkoda app?

> This integration currently only supports the old Skoda API compatible with the old Skoda Essentials App.
>
> If you are unable to use the Skoda Essentials account the integration will not work for you. This is the case for new vehicles and/or Skoda accounts.
> 
> We are aware the Skoda Essentials app is being deprecated and are working on updating the integration to be compatible with the new API / MySkoda app, but this is a major piece of development work.
> 
> Please do not open new issues for this.

**Comment by astrakid** [comment]
no, i can only use the new one. that was the reason why i wasn't able to use evcc as well. after fixing the api in evcc i am able to use it there. so i am sure that the api needs to be fixed. with july 1st 2025 it will be the case for the "old users" as well, because the old api will be switched off.
